version: '3.1'

services:
  db:
    image: madb:latest
    container_name: db-container
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: parc_informatique
      MARIADB_USER: user1
      MARIADB_PASSWORD: user1
    volumes:
      - data:/var/lib/mysql
    networks:
      - myappnet
    
  pythonapp:
    depends_on:
      - db
    image: pyapp:latest  
    container_name: py-container
    stdin_open: true
    tty: true
    networks:
      - myappnet

volumes:
  data:

networks:
  myappnet:
    driver: bridge
